In [10]:
from verycloudy.config import DATA_DIR, FILEPATH_CLOUDS_CSV, FILEPATH_CLOUDS_APPEND_CSV, FILEPATH_CLOUDS_JSON, FILEPATH_CLOUDS_APPEND_JSON, FILEPATH_CLOUDS_TEST, FILEPATH_DATE_TEST, FILEPATH_DATE_CSV

In [2]:
import pandas as pd

In [ ]:
df1 = pd.read_csv(FILEPATH_CLOUDS_CSV)
df2 = pd.read_csv(FILEPATH_CLOUDS_APPEND_CSV)

combined = pd.concat([df1, df2], ignore_index=True)

combined.to_csv(DATA_DIR / "combined.csv", index=False)

In [4]:
with open(DATA_DIR / "combined.jsonl", "w", encoding="utf-8") as out:
    for fname in [FILEPATH_CLOUDS_JSON, FILEPATH_CLOUDS_APPEND_JSON]:
        with open(fname, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    out.write(line)

In [3]:
df = pd.read_csv(FILEPATH_CLOUDS_CSV)
sample = df.sample(n=1000, random_state=42)  

sample.to_csv(FILEPATH_CLOUDS_TEST, index=False)

In [6]:
row = sample[sample["lightbox_id"] == 19317]
display(row)

,lightbox_id,image_url,date_iso,date_raw,author_name,author_profile,title,tags
22855,19317,https://cloudappreciationsociety.org/wp-conten...,2009-08-28,"August 28, 2009",© Paola Seardo.,//photographer/paola-seardo,"Mammatus, spotted following a storm near Torin...","A classic example, Our favourites, Mamma"

In [7]:
sample_date = pd.read_csv(FILEPATH_DATE_TEST)

sample_date["error"].value_counts()

error
fallback to upload               577
capture in filename              269
capture in metadata              149
HTTP 404 + fallback to upload      5
Name: count, dtype: int64

In [8]:
rows = sample_date[sample_date["error"] == "HTTP 404 + fallback to upload"]
display(rows)

,lightbox_id,image_url,status,date_taken,time_taken,date_taken_utc,time_taken_utc,source_field,fallback_used,error
67,38485,https://cloudappreciationsociety.org/wp-conten...,404,2013-03-01,11:00:00,NaN,NaN,NaN,True,HTTP 404 + fallback to upload
319,19447,https://cloudappreciationsociety.org/wp-conten...,404,2009-09-07,11:00:00,NaN,NaN,NaN,True,HTTP 404 + fallback to upload
935,20613,https://cloudappreciationsociety.org/wp-conten...,404,2010-02-08,11:00:00,NaN,NaN,NaN,True,HTTP 404 + fallback to upload
938,22901,https://cloudappreciationsociety.org/wp-conten...,404,2011-01-20,11:00:00,NaN,NaN,NaN,True,HTTP 404 + fallback to upload
990,19317,https://cloudappreciationsociety.org/wp-conten...,404,2009-08-28,11:00:00,NaN,NaN,NaN,True,HTTP 404 + fallback to upload

In [11]:
date = pd.read_csv(FILEPATH_DATE_CSV)

date["error"].value_counts()

error
fallback to upload                    16720
capture in filename                    7328
capture in metadata                    4425
HTTP 404 + fallback to upload            71
Network error + fallback to upload       33
Name: count, dtype: int64