In [2]:
from verycloudy.config import DATA_DIR, FILEPATH_CLOUDS_CSV, FILEPATH_CLOUDS_APPEND_CSV, FILEPATH_CLOUDS_JSON, FILEPATH_CLOUDS_APPEND_JSON, FILEPATH_CLOUDS_TEST, FILEPATH_DATE_TEST, FILEPATH_DATE_CSV

In [7]:
import pandas as pd

In [ ]:
df1 = pd.read_csv(FILEPATH_CLOUDS_CSV)
df2 = pd.read_csv(FILEPATH_CLOUDS_APPEND_CSV)

combined = pd.concat([df1, df2], ignore_index=True)

combined.to_csv(DATA_DIR / "combined.csv", index=False)

In [4]:
with open(DATA_DIR / "combined.jsonl", "w", encoding="utf-8") as out:
    for fname in [FILEPATH_CLOUDS_JSON, FILEPATH_CLOUDS_APPEND_JSON]:
        with open(fname, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    out.write(line)

In [3]:
df = pd.read_csv(FILEPATH_CLOUDS_CSV)
sample = df.sample(n=1000, random_state=42)  

sample.to_csv(FILEPATH_CLOUDS_TEST, index=False)

In [6]:
row = sample[sample["lightbox_id"] == 19317]
display(row)

,lightbox_id,image_url,date_iso,date_raw,author_name,author_profile,title,tags
22855,19317,https://cloudappreciationsociety.org/wp-conten...,2009-08-28,"August 28, 2009",© Paola Seardo.,//photographer/paola-seardo,"Mammatus, spotted following a storm near Torin...","A classic example, Our favourites, Mamma"

In [7]:
sample_date = pd.read_csv(FILEPATH_DATE_TEST)

sample_date["error"].value_counts()

error
fallback to upload               577
capture in filename              269
capture in metadata              149
HTTP 404 + fallback to upload      5
Name: count, dtype: int64

In [8]:
rows = sample_date[sample_date["error"] == "HTTP 404 + fallback to upload"]
display(rows)

,lightbox_id,image_url,status,date_taken,time_taken,date_taken_utc,time_taken_utc,source_field,fallback_used,error
67,38485,https://cloudappreciationsociety.org/wp-conten...,404,2013-03-01,11:00:00,NaN,NaN,NaN,True,HTTP 404 + fallback to upload
319,19447,https://cloudappreciationsociety.org/wp-conten...,404,2009-09-07,11:00:00,NaN,NaN,NaN,True,HTTP 404 + fallback to upload
935,20613,https://cloudappreciationsociety.org/wp-conten...,404,2010-02-08,11:00:00,NaN,NaN,NaN,True,HTTP 404 + fallback to upload
938,22901,https://cloudappreciationsociety.org/wp-conten...,404,2011-01-20,11:00:00,NaN,NaN,NaN,True,HTTP 404 + fallback to upload
990,19317,https://cloudappreciationsociety.org/wp-conten...,404,2009-08-28,11:00:00,NaN,NaN,NaN,True,HTTP 404 + fallback to upload

In [11]:
date = pd.read_csv(FILEPATH_DATE_CSV)

date["error"].value_counts()

error
fallback to upload                    16720
capture in filename                    7328
capture in metadata                    4425
HTTP 404 + fallback to upload            71
Network error + fallback to upload       33
Name: count, dtype: int64

In [5]:
# Load the CSV files
df1 = pd.read_csv(FILEPATH_CLOUDS_CSV)
df2 = pd.read_csv(FILEPATH_DATE_CSV)

df2 = df2.drop(columns=["image_url"]) 

# Merge on lightbox_id
merged = pd.merge(df1, df2, on="lightbox_id", how="left")

# Save result
merged.to_csv(DATA_DIR / 'cloud_gallery_with_date.csv', index=False)

In [6]:
sample = merged.sample(n=1000, random_state=42)  

sample.to_csv(DATA_DIR / "cloud_gallery_with_date_testset.csv", index=False)

In [8]:
location = pd.read_csv(DATA_DIR / "clouds_location_test.csv")

location["location_source"].value_counts()

location_source
title       823
metadata     49
Name: count, dtype: int64

In [11]:
df = pd.read_csv(FILEPATH_CLOUDS_CSV)

row = df[df["lightbox_id"] == 622301]
row2 = location[location["lightbox_id"] == 622301]
display(row)
display(row2)

,lightbox_id,image_url,date_iso,date_raw,author_name,author_profile,title,tags
3441,622301,https://cloudappreciationsociety.org/wp-conten...,2024-10-21,"October 21, 2024",© Ye Yongcheng,//photographer/-,A mirror reflection of the sky over Vietnam,"Our favourites, Cumulus, Cirrus, Congestus"

     lightbox_id     city region country  latitude  longitude location_source
449       622301  vietnam  Sucre      CO  9.697039 -75.616098           title

In [28]:
id = 13629
row = df[df["lightbox_id"] == id]
row2 = location[location["lightbox_id"] == id]
title = row["title"]
display(row)
display(title)
display(row2)

,lightbox_id,image_url,date_iso,date_raw,author_name,author_profile,title,tags
25397,13629,https://cloudappreciationsociety.org/wp-conten...,2007-07-04,"July 4, 2007",© Bruno Aguiari.,//photographer/bruno-aguiari,"Taken from a plane above the Alps, on a journe...","Our favourites, Cumulus, Altocumulus, Cumuloni..."

25397    Taken from a plane above the Alps, on a journe...
Name: title, dtype: object

     lightbox_id city region country  latitude  longitude location_source
861        13629  NaN    NaN     NaN       NaN        NaN             NaN

In [20]:
df['title'].isna().sum() + df['title'].eq("").sum()

134

In [21]:
location.columns

Index(['lightbox_id', 'city', 'region', 'country', 'latitude', 'longitude',
       'location_source'],
      dtype='object')

In [26]:
location['latitude'].isna().sum() + location['latitude'].eq("").sum()

128